# Generated by Django 3.2 on 2025-05-21 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakerystore', '0008_alter_orderlist_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('done', 'Done'), ('canceled', 'Canceled')], db_index=True, default='pending', max_length=10),
        ),
    ]
